development:
  adapter: postgresql
  encoding: utf8
  database: LogIn_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: LogIN_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: LogIn_production
  pool: 5
  username: 
  password:

cucumber:
  <<: *TEST